In [1]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [2]:
import nltk

# Essential downloads

nltk.download('punkt')

nltk.download('stopwords')

nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [3]:
from nltk.tokenize import sent_tokenize

nltk.download('punkt_tab')

s = "I love ice cream. My favourite ice cream is chocolate. It has a lot of flavour."

t_s = sent_tokenize(s)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [4]:
print(t_s)

['I love ice cream.', 'My favourite ice cream is chocolate.', 'It has a lot of flavour.']

In [5]:
from nltk.tokenize import word_tokenize

s = "I love ice cream. My favourite ice cream is chocolate. It has a lot of flavour."

w_s = word_tokenize(s)

In [6]:
print(w_s)

['I', 'love', 'ice', 'cream', '.', 'My', 'favourite', 'ice', 'cream', 'is', 'chocolate', '.', 'It', 'has', 'a', 'lot', 'of', 'flavour', '.']

In [7]:
from nltk.corpus import stopwords
nltk.download('stopwords')

words = w_s

stop_words = set(stopwords.words('english'))

cleaned = [w.lower() for w in words
           if w.lower() not in stop_words]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [8]:
print(cleaned)

['love', 'ice', 'cream', '.', 'favourite', 'ice', 'cream', 'chocolate', '.', 'lot', 'flavour', '.']

In [9]:
from nltk.stem import PorterStemmer , WordNetLemmatizer

nltk.download('wordnet')

stemmer = PorterStemmer()
lem = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [10]:
print(stemmer.stem("lightning"))

lightn

In [11]:
print(lem.lemmatize("running" , pos ="v")) # v = verb

run

In [12]:
print(lem.lemmatize("better" , pos ="a")) # a = adjective

good

In [13]:
print(lem.lemmatize("quickly" , pos = "r")) # r = adverb

quickly

In [14]:
print(lem.lemmatize("cars" , pos ="n")) # n = noun

car

In [15]:
from nltk import pos_tag, ne_chunk

nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker_tab')
nltk.download('words')

tokens = word_tokenize("Steve Jobs founded Apple.")
tags = pos_tag(tokens)
entities = ne_chunk(tags)

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

In [16]:
print(tags)

[('Steve', 'NNP'), ('Jobs', 'NNP'), ('founded', 'VBD'), ('Apple', 'NNP'), ('.', '.')]

In [17]:
print(entities)

(S
  (PERSON Steve/NNP)
  (PERSON Jobs/NNP)
  founded/VBD
  (PERSON Apple/NNP)
  ./.)

In [18]:
from nltk import FreqDist

text = "I love ice cream. My favourite ice cream is chocolate. It has a lot of flavour."

words = word_tokenize(text)

fdist = FreqDist(words)

print(fdist.most_common(5))

[('.', 3), ('ice', 2), ('cream', 2), ('I', 1), ('love', 1)]

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("/content/train.csv")

In [21]:
df.head()

,Unnamed: 0,label,title,description,text,category
0,0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli...",Wall St. Bears Claw Back Into the Black (Reute...,Business
1,1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...,Carlyle Looks Toward Commercial Aerospace (Reu...,Business
2,2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...,Oil and Economy Cloud Stocks' Outlook (Reuters...,Business
3,3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...,Iraq Halts Oil Exports from Main Southern Pipe...,Business
4,4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco...","Oil prices soar to all-time record, posing new...",Business

In [22]:
df["text"][0]

"Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\\band of ultra-cynics, are seeing green again."

In [24]:
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [25]:
df["category"].unique()

array(['Business', 'Sci/Tech', 'Sports', 'World'], dtype=object)

In [26]:
df["category"].nunique()

4

In [27]:
df["category"].value_counts()

category
Business    30000
Sci/Tech    30000
Sports      30000
World       30000
Name: count, dtype: int64

In [28]:
df2 = pd.read_csv("/content/test.csv")

In [32]:
len(df) # Training

120000

In [31]:
len(df2) # Testing

7600

In [33]:
nltk.download('punkt')

nltk.download('stopwords')

nltk.download("punkt_tab")

nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Pre-Processing


1. All the text ---> lowercase
2. Tokenise the sentence ---> words
3. Remove Stopwords (the , is , ...)
4. Removing Punctutaion (! , .)
5. Join everything which is remaining.

In [35]:
stop_words = set(stopwords.words("english"))

In [38]:
# Function

def preprocess(text):

    text = text.lower()

    words = word_tokenize(text)

    words = [ word
            for word in words
            if word.isalpha() and word not in stop_words ]

    return " ".join(words)

In [41]:
sample = df["text"][0]

print(sample)

Wall St. Bears Claw Back Into the Black (Reuters) Reuters - Short-sellers, Wall Street's dwindling\band of ultra-cynics, are seeing green again.

In [42]:
pro = preprocess(sample)

print(pro)

wall bears claw back black reuters reuters wall street seeing green

In [43]:
# Training Data

df["clean_text"] = df['text'].apply(preprocess)

# Testing Data

df2["clean_text"] = df2['text'].apply(preprocess)

In [44]:
df.head()

,Unnamed: 0,label,title,description,text,category,clean_text
0,0,3,Wall St. Bears Claw Back Into the Black (Reuters),"Reuters - Short-sellers, Wall Street's dwindli...",Wall St. Bears Claw Back Into the Black (Reute...,Business,wall bears claw back black reuters reuters wal...
1,1,3,Carlyle Looks Toward Commercial Aerospace (Reu...,Reuters - Private investment firm Carlyle Grou...,Carlyle Looks Toward Commercial Aerospace (Reu...,Business,carlyle looks toward commercial aerospace reut...
2,2,3,Oil and Economy Cloud Stocks' Outlook (Reuters),Reuters - Soaring crude prices plus worries\ab...,Oil and Economy Cloud Stocks' Outlook (Reuters...,Business,oil economy cloud stocks outlook reuters reute...
3,3,3,Iraq Halts Oil Exports from Main Southern Pipe...,Reuters - Authorities have halted oil export\f...,Iraq Halts Oil Exports from Main Southern Pipe...,Business,iraq halts oil exports main southern pipeline ...
4,4,3,"Oil prices soar to all-time record, posing new...","AFP - Tearaway world oil prices, toppling reco...","Oil prices soar to all-time record, posing new...",Business,oil prices soar record posing new menace us ec...

In [45]:
X_train = df['clean_text']

X_test =  df2['clean_text']

y_train = df['category']

y_test = df2['category']

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer( max_features = 10000)

In [49]:
X_train_tf = vec.fit_transform(X_train)

X_test_tf = vec.transform(X_test)

In [54]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter= 1000)

model.fit(X_train_tf , y_train)

LogisticRegression(max_iter=1000)

In [56]:
y_pred = model.predict(X_test_tf)

In [57]:
y_pred[:10]

array(['Business', 'Sci/Tech', 'Sci/Tech', 'Sci/Tech', 'Sci/Tech',
       'Sci/Tech', 'Sci/Tech', 'Sci/Tech', 'Sci/Tech', 'Sci/Tech'],
      dtype=object)

In [59]:
from sklearn.metrics import accuracy_score , classification_report

acc = accuracy_score(y_test , y_pred)

print(acc * 100)

91.17105263157896

In [75]:
new_article = """
A new law limits mega-investor home purchases. Will that make homes cheaper for Americans?
"""

In [76]:
clean = preprocess(new_article)

article_vec = vec.transform([clean])

In [77]:
p1 = model.predict(article_vec)

In [78]:
print(p1)

['World']